version: "3.4"
services:
  library:
    build:
      context: .
    environment:
      - LIBRARY_SECRET=um-segredo
    link:
      mongo
    depends_on:
      mongo
        condition: service_healthy
    networks:
      - mongo-compose-network
  mongo:
    image: mongo:3.6.0
    command: ["--bind_ip_all"]
    tmpfs: /data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge