apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'library'
  namespace: luizbento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library
        image: dyegomaas/library:latest
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 80
        env:
          - name: "LIBRARY_SECRET"
            valueFrom:
              secretKeyRef:
                key:  library-secret
                name: library-auth
          - name: "CONNECTION_TIMEOUT_MS"
            value: "30000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: luizbento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017